- name: Setup sunbird-dial-service as service
  become: yes
  template: src=servicify-process.j2 dest={{ service_path }}/{{ script_name }} mode=755 owner={{ learner_user }} group={{ learner_group }}

